openapi: 3.0.3
info:
  title: Laravel
  description: ''
  version: 1.0.0
servers:
  -
    url: 'http://localhost'
paths:
  /api/user:
    get:
      summary: ''
      operationId: getApiUser
      description: ''
      parameters: []
      responses:
        401:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: Unauthenticated.
                properties:
                  message:
                    type: string
                    example: Unauthenticated.
      tags:
        - Endpoints
      security: []
  /api/lists/categories:
    get:
      summary: ''
      operationId: getApiListsCategories
      description: ''
      parameters: []
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  data:
                    -
                      id: 1
                      name: 'perferendis voluptatem laboriosam'
                    -
                      id: 2
                      name: 'similique illum dolorem'
                    -
                      id: 3
                      name: 'expedita similique fugit'
                    -
                      id: 4
                      name: 'ullam ad voluptatum'
                    -
                      id: 5
                      name: 'necessitatibus explicabo corporis'
                    -
                      id: 6
                      name: 'aut veritatis totam'
                    -
                      id: 7
                      name: 'ipsam non deleniti'
                    -
                      id: 8
                      name: 'molestias ipsam impedit'
                    -
                      id: 9
                      name: 'incidunt repellat ut'
                    -
                      id: 10
                      name: 'odit qui omnis'
                properties:
                  data:
                    type: array
                    example:
                      -
                        id: 1
                        name: 'perferendis voluptatem laboriosam'
                      -
                        id: 2
                        name: 'similique illum dolorem'
                      -
                        id: 3
                        name: 'expedita similique fugit'
                      -
                        id: 4
                        name: 'ullam ad voluptatum'
                      -
                        id: 5
                        name: 'necessitatibus explicabo corporis'
                      -
                        id: 6
                        name: 'aut veritatis totam'
                      -
                        id: 7
                        name: 'ipsam non deleniti'
                      -
                        id: 8
                        name: 'molestias ipsam impedit'
                      -
                        id: 9
                        name: 'incidunt repellat ut'
                      -
                        id: 10
                        name: 'odit qui omnis'
                    items:
                      type: object
                      properties:
                        id:
                          type: integer
                          example: 1
                        name:
                          type: string
                          example: 'perferendis voluptatem laboriosam'
      tags:
        - Endpoints
      security: []
  /api/categories:
    get:
      summary: ''
      operationId: getApiCategories
      description: ''
      parameters: []
      responses:
        401:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: Unauthenticated.
                properties:
                  message:
                    type: string
                    example: Unauthenticated.
      tags:
        - Endpoints
      security: []
    post:
      summary: ''
      operationId: postApiCategories
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: ''
                  example: eaque
                  nullable: false
              required:
                - name
      security: []
  '/api/categories/{id}':
    get:
      summary: ''
      operationId: getApiCategoriesId
      description: ''
      parameters: []
      responses:
        401:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: Unauthenticated.
                properties:
                  message:
                    type: string
                    example: Unauthenticated.
      tags:
        - Endpoints
      security: []
    put:
      summary: ''
      operationId: putApiCategoriesId
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: ''
                  example: porro
                  nullable: false
              required:
                - name
      security: []
    delete:
      summary: ''
      operationId: deleteApiCategoriesId
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      security: []
    parameters:
      -
        in: path
        name: id
        description: 'The ID of the category.'
        example: 1
        required: true
        schema:
          type: integer
  /api/products:
    get:
      summary: ''
      operationId: getApiProducts
      description: ''
      parameters: []
      responses:
        401:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: Unauthenticated.
                properties:
                  message:
                    type: string
                    example: Unauthenticated.
      tags:
        - Endpoints
      security: []
tags:
  -
    name: Endpoints
    description: ''
